// front-end-react/src/layouts/MainLayout.tsx
import { Outlet } from 'react-router-dom'
import Navbar from '../components/Navbar'
import Sidebar from '../components/Sidebar'
import { useAuth } from '../auth/AuthContext'
import './MainLayout.css'

export default function MainLayout() {
  const { isAuthenticated } = useAuth()

  return (
    <div className="min-h-screen bg-slate-50">
      <Sidebar />
      <div className={isAuthenticated ? 'main-content-authenticated' : ''}>
        <Navbar />
        <main className="p-4">
          <Outlet />
        </main>
      </div>
    </div>
  )
}

// front-end/src/layouts/MainLayout.vue
<!-- layouts/MainLayout.vue -->
<script setup>
import Navbar from '../components/Navbar.vue'
import Sidebar from '../components/Sidebar.vue'
import { authState } from '../store/auth'
import { computed } from 'vue'

const isAuthenticated = computed(() => authState.isAuthenticated)
</script>

<template>
  <div class="min-h-screen bg-slate-50">
    <Sidebar />
    <div :class="{ 'main-content-authenticated': isAuthenticated }">
      <Navbar />
      <main class="p-4">
        <router-view />
      </main>
    </div>
  </div>
</template>

<style scoped>
.main-content-authenticated {
  margin-left: 64px;
  transition: margin-left 0.3s ease;
  width: calc(100% - 64px);
}
</style>
